### ISSUE TITLE
Unable to get this to work with PhoneGap 1.1.0 and facebook-ios-sdk (91f256424)

### ISSUE THREAD

**Issue by carl** [Wizcorp/phonegap-facebook-plugin#54]
As others have posted elsewhere, could only get this to work by downgrading to PhoneGap 1.0.0 (can find and install from github tag).  With 1.1.0 could get it to compile, but then it wouldn't link properly, failing with:

Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_Facebook", referenced from:
      objc-class-ref in FacebookConnectPlugin-375760CB59A4DB21.o
     (maybe you meant: _OBJC_CLASS_$_FacebookConnectPlugin)
ld: symbol(s) not found for architecture i386

even though using lipo command line tool showed the .a file was i386 and nm command showed that symbol, and had several more experienced iOS developers look at it to verify was building and linking properly.
