### ISSUE TITLE
Crash phonegap build on 0.11.0

### ISSUE THREAD

**Issue by bluepioupiou** [Wizcorp/phonegap-facebook-plugin#929]
Now that the 0.11.0 version is on corodva registry, I've got an error trying to build it with phonegap

 - on iOS : CompileC build/Unlishtest.build/Release-iphoneos/Unlishtest.build/Objects-normal/armv7/FacebookConnectPlugin.o Unlishtest/Plugins/com.phonegap.plugins.facebookconnect/FacebookConnectPlugin.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
 - on Android : /project/com.phonegap.plugins.facebookconnect/FacebookLib/custom_rules.xml:4: /project/com.phonegap.plugins.facebookconnect/FacebookLib/ant-build does not exist.

is that normal ?

**Comment by aogilvie** [comment]
@bluepioupiou Assuming you installed like;

` cordova plugin add com.phonegap.plugins.facebookconnect --variable APP_ID="1234567" --variable APP_NAME="Something"` - from the registry id.

iOS is broken because plugman (the tool behind the CLI) cannot publish a .framework file and retain the sym links. ***So after your build command you need to open the Xcode project and re-add the Facebook.framework. :(

This is the full error you should get:
 
```
In file included from /Users/ogilvie/Documents/aogilvie/testFB/myApp/platforms/ios/HelloCordova/Plugins/com.phonegap.plugins.facebookconnect/FacebookConnectPlugin.m:11:
HelloCordova/Plugins/com.phonegap.plugins.facebookconnect/FacebookConnectPlugin.h:11:9: fatal error: 'FacebookSDK/FacebookSDK.h' file not found
#import <FacebookSDK/FacebookSDK.h>
        ^
1 error generated.

** BUILD FAILED **


The following build commands failed:
	CompileC build/HelloCordova.build/Debug-iphonesimulator/HelloCordova.build/Objects-normal/i386/FacebookConnectPlugin.o HelloCordova/Plugins/com.phonegap.plugins.facebookconnect/FacebookConnectPlugin.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
```

That Android error is strange. I'm looking into it now.

**Comment by bluepioupiou** [comment]
Hmmm the iOS erreur only appeared when I was using this plugin on a mac to build directly on my iPhone for test purpose. I've used the workaround already. 

But here it's with phonegap build, which with the 0.10.1 or older version never caused me an issue

**Comment by aogilvie** [comment]
@bluepioupiou do you have a larger error console output for iOS? I can't test PhoneGap Build we don't support it :/

**Comment by bluepioupiou** [comment]
of course, thanks for your help

CompileC build/Unlishtest.build/Release-iphoneos/Unlishtest.build/Objects-normal/armv7/FacebookConnectPlugin.o Unlishtest/Plugins/com.phonegap.plugins.facebookconnect/FacebookConnectPlugin.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /project
    export LANG=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch armv7 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=c99 -fobjc-arc -Wno-trigraphs -fpascal-strings -Os -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-receiver-is-weak -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DCORDOVA_FRAMEWORK=1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -fvisibility=hidden -Wno-sign-conversion -miphoneos-version-min=6.0 -iquote /project/build/Unlishtest.build/Release-iphoneos/Unlishtest.build/Unlishtest-generated-files.hmap -I/project/build/Unlishtest.build/Release-iphoneos/Unlishtest.build/Unlishtest-own-target-headers.hmap -I/project/build/Unlishtest.build/Release-iphoneos/Unlishtest.build/Unlishtest-all-target-headers.hmap -iquote /project/build/Unlishtest.build/Release-iphoneos/Unlishtest.build/Unlishtest-project-headers.hmap -I/project/build/include -I/project/build/usr/local/lib/include -I/project/build/UninstalledProducts/include -I/project/build -I/project/build/Unlishtest.build/Release-iphoneos/Unlishtest.build/DerivedSources/armv7 -I/project/build/Unlishtest.build/Release-iphoneos/Unlishtest.build/DerivedSources -F/project/build -FUnlishtest/Plugins/com.phonegap.plugins.facebookconnect -include /var/folders/8r/065_jhkn1qqf03lr71kjj6480000gp/C/com.apple.DeveloperTools/6.1-6A1052d/Xcode/SharedPrecompiledHeaders/Unlishtest-Prefix-geicatlkylamwwgbsgzrsvkdialx/Unlishtest-Prefix.pch -MMD -MT dependencies -MF /project/build/Unlishtest.build/Release-iphoneos/Unlishtest.build/Objects-normal/armv7/FacebookConnectPlugin.d --serialize-diagnostics /project/build/Unlishtest.build/Release-iphoneos/Unlishtest.build/Objects-normal/armv7/FacebookConnectPlugin.dia -c /project/Unlishtest/Plugins/com.phonegap.plugins.facebookconnect/FacebookConnectPlugin.m -o /project/build/Unlishtest.build/Release-iphoneos/Unlishtest.build/Objects-normal/armv7/FacebookConnectPlugin.o
In file included from /project/Unlishtest/Plugins/com.phonegap.plugins.facebookconnect/FacebookConnectPlugin.m:11:
Unlishtest/Plugins/com.phonegap.plugins.facebookconnect/FacebookConnectPlugin.h:11:9: fatal error: 'FacebookSDK/FacebookSDK.h' file not found
#import <FacebookSDK/FacebookSDK.h>
        ^
1 error generated.

CompileC build/Unlishtest.build/Release-iphoneos/Unlishtest.build/Objects-normal/armv7/CDVSplashScreen.o Unlishtest/Plugins/org.apache.cordova.splashscreen/CDVSplashScreen.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /project
    export LANG=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch armv7 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=c99 -fobjc-arc -Wno-trigraphs -fpascal-strings -Os -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-receiver-is-weak -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DCORDOVA_FRAMEWORK=1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -fvisibility=hidden -Wno-sign-conversion -miphoneos-version-min=6.0 -iquote /project/build/Unlishtest.build/Release-iphoneos/Unlishtest.build/Unlishtest-generated-files.hmap -I/project/build/Unlishtest.build/Release-iphoneos/Unlishtest.build/Unlishtest-own-target-headers.hmap -I/project/build/Unlishtest.build/Release-iphoneos/Unlishtest.build/Unlishtest-all-target-headers.hmap -iquote /project/build/Unlishtest.build/Release-iphoneos/Unlishtest.build/Unlishtest-project-headers.hmap -I/project/build/include -I/project/build/usr/local/lib/include -I/project/build/UninstalledProducts/include -I/project/build -I/project/build/Unlishtest.build/Release-iphoneos/Unlishtest.build/DerivedSources/armv7 -I/project/build/Unlishtest.build/Release-iphoneos/Unlishtest.build/DerivedSources -F/project/build -FUnlishtest/Plugins/com.phonegap.plugins.facebookconnect -include /var/folders/8r/065_jhkn1qqf03lr71kjj6480000gp/C/com.apple.DeveloperTools/6.1-6A1052d/Xcode/SharedPrecompiledHeaders/Unlishtest-Prefix-geicatlkylamwwgbsgzrsvkdialx/Unlishtest-Prefix.pch -MMD -MT dependencies -MF /project/build/Unlishtest.build/Release-iphoneos/Unlishtest.build/Objects-normal/armv7/CDVSplashScreen.d --serialize-diagnostics /project/build/Unlishtest.build/Release-iphoneos/Unlishtest.build/Objects-normal/armv7/CDVSplashScreen.dia -c /project/Unlishtest/Plugins/org.apache.cordova.splashscreen/CDVSplashScreen.m -o /project/build/Unlishtest.build/Release-iphoneos/Unlishtest.build/Objects-normal/armv7/CDVSplashScreen.o

CompileC build/Unlishtest.build/Release-iphoneos/Unlishtest.build/Objects-normal/armv7/CDVInAppBrowser.o Unlishtest/Plugins/org.apache.cordova.inappbrowser/CDVInAppBrowser.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /project
    export LANG=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch armv7 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=c99 -fobjc-arc -Wno-trigraphs -fpascal-strings -Os -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-receiver-is-weak -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DCORDOVA_FRAMEWORK=1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -fvisibility=hidden -Wno-sign-conversion -miphoneos-version-min=6.0 -iquote /project/build/Unlishtest.build/Release-iphoneos/Unlishtest.build/Unlishtest-generated-files.hmap -I/project/build/Unlishtest.build/Release-iphoneos/Unlishtest.build/Unlishtest-own-target-headers.hmap -I/project/build/Unlishtest.build/Release-iphoneos/Unlishtest.build/Unlishtest-all-target-headers.hmap -iquote /project/build/Unlishtest.build/Release-iphoneos/Unlishtest.build/Unlishtest-project-headers.hmap -I/project/build/include -I/project/build/usr/local/lib/include -I/project/build/UninstalledProducts/include -I/project/build -I/project/build/Unlishtest.build/Release-iphoneos/Unlishtest.build/DerivedSources/armv7 -I/project/build/Unlishtest.build/Release-iphoneos/Unlishtest.build/DerivedSources -F/project/build -FUnlishtest/Plugins/com.phonegap.plugins.facebookconnect -include /var/folders/8r/065_jhkn1qqf03lr71kjj6480000gp/C/com.apple.DeveloperTools/6.1-6A1052d/Xcode/SharedPrecompiledHeaders/Unlishtest-Prefix-geicatlkylamwwgbsgzrsvkdialx/Unlishtest-Prefix.pch -MMD -MT dependencies -MF /project/build/Unlishtest.build/Release-iphoneos/Unlishtest.build/Objects-normal/armv7/CDVInAppBrowser.d --serialize-diagnostics /project/build/Unlishtest.build/Release-iphoneos/Unlishtest.build/Objects-normal/armv7/CDVInAppBrowser.dia -c /project/Unlishtest/Plugins/org.apache.cordova.inappbrowser/CDVInAppBrowser.m -o /project/build/Unlishtest.build/Release-iphoneos/Unlishtest.build/Objects-normal/armv7/CDVInAppBrowser.o

CompileC build/Unlishtest.build/Release-iphoneos/Unlishtest.build/Objects-normal/armv7/CDVDevice.o Unlishtest/Plugins/org.apache.cordova.device/CDVDevice.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /project
    export LANG=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch armv7 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=c99 -fobjc-arc -Wno-trigraphs -fpascal-strings -Os -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-receiver-is-weak -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DCORDOVA_FRAMEWORK=1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -fvisibility=hidden -Wno-sign-conversion -miphoneos-version-min=6.0 -iquote /project/build/Unlishtest.build/Release-iphoneos/Unlishtest.build/Unlishtest-generated-files.hmap -I/project/build/Unlishtest.build/Release-iphoneos/Unlishtest.build/Unlishtest-own-target-headers.hmap -I/project/build/Unlishtest.build/Release-iphoneos/Unlishtest.build/Unlishtest-all-target-headers.hmap -iquote /project/build/Unlishtest.build/Release-iphoneos/Unlishtest.build/Unlishtest-project-headers.hmap -I/project/build/include -I/project/build/usr/local/lib/include -I/project/build/UninstalledProducts/include -I/project/build -I/project/build/Unlishtest.build/Release-iphoneos/Unlishtest.build/DerivedSources/armv7 -I/project/build/Unlishtest.build/Release-iphoneos/Unlishtest.build/DerivedSources -F/project/build -FUnlishtest/Plugins/com.phonegap.plugins.facebookconnect -include /var/folders/8r/065_jhkn1qqf03lr71kjj6480000gp/C/com.apple.DeveloperTools/6.1-6A1052d/Xcode/SharedPrecompiledHeaders/Unlishtest-Prefix-geicatlkylamwwgbsgzrsvkdialx/Unlishtest-Prefix.pch -MMD -MT dependencies -MF /project/build/Unlishtest.build/Release-iphoneos/Unlishtest.build/Objects-normal/armv7/CDVDevice.d --serialize-diagnostics /project/build/Unlishtest.build/Release-iphoneos/Unlishtest.build/Objects-normal/armv7/CDVDevice.dia -c /project/Unlishtest/Plugins/org.apache.cordova.device/CDVDevice.m -o /project/build/Unlishtest.build/Release-iphoneos/Unlishtest.build/Objects-normal/armv7/CDVDevice.o

CompileC build/Unlishtest.build/Release-iphoneos/Unlishtest.build/Objects-normal/armv7/UIImage+CropScaleOrientation.o Unlishtest/Plugins/org.apache.cordova.camera/UIImage+CropScaleOrientation.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /project
    export LANG=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch armv7 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=c99 -fobjc-arc -Wno-trigraphs -fpascal-strings -Os -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-receiver-is-weak -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DCORDOVA_FRAMEWORK=1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -fvisibility=hidden -Wno-sign-conversion -miphoneos-version-min=6.0 -iquote /project/build/Unlishtest.build/Release-iphoneos/Unlishtest.build/Unlishtest-generated-files.hmap -I/project/build/Unlishtest.build/Release-iphoneos/Unlishtest.build/Unlishtest-own-target-headers.hmap -I/project/build/Unlishtest.build/Release-iphoneos/Unlishtest.build/Unlishtest-all-target-headers.hmap -iquote /project/build/Unlishtest.build/Release-iphoneos/Unlishtest.build/Unlishtest-project-headers.hmap -I/project/build/include -I/project/build/usr/local/lib/include -I/project/build/UninstalledProducts/include -I/project/build -I/project/build/Unlishtest.build/Release-iphoneos/Unlishtest.build/DerivedSources/armv7 -I/project/build/Unlishtest.build/Release-iphoneos/Unlishtest.build/DerivedSources -F/project/build -FUnlishtest/Plugins/com.phonegap.plugins.facebookconnect -include /var/folders/8r/065_jhkn1qqf03lr71kjj6480000gp/C/com.apple.DeveloperTools/6.1-6A1052d/Xcode/SharedPrecompiledHeaders/Unlishtest-Prefix-geicatlkylamwwgbsgzrsvkdialx/Unlishtest-Prefix.pch -MMD -MT dependencies -MF /project/build/Unlishtest.build/Release-iphoneos/Unlishtest.build/Objects-normal/armv7/UIImage+CropScaleOrientation.d --serialize-diagnostics /project/build/Unlishtest.build/Release-iphoneos/Unlishtest.build/Objects-normal/armv7/UIImage+CropScaleOrientation.dia -c /project/Unlishtest/Plugins/org.apache.cordova.camera/UIImage+CropScaleOrientation.m -o /project/build/Unlishtest.build/Release-iphoneos/Unlishtest.build/Objects-normal/armv7/UIImage+CropScaleOrientation.o

** BUILD FAILED **


The following build commands failed:
	CompileC build/Unlishtest.build/Release-iphoneos/Unlishtest.build/Objects-normal/armv7/FacebookConnectPlugin.o Unlishtest/Plugins/com.phonegap.plugins.facebookconnect/FacebookConnectPlugin.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

**Comment by aogilvie** [comment]
@bluepioupiou Regarding Android: I cannot reproduce the Android error from a fresh project using:

```
cordova create myApp
cd myApp
cordova platform add ios android
cordova plugin add com.phonegap.plugins.facebookconnect --variable APP_ID="1234567" --variable APP_NAME="Something"
cordova build android
```

**Comment by aogilvie** [comment]
@bluepioupiou yeah for iOS you have the error, not at the bottom of your output but a little further up:

```
In file included from /project/Unlishtest/Plugins/com.phonegap.plugins.facebookconnect/FacebookConnectPlugin.m:11:
Unlishtest/Plugins/com.phonegap.plugins.facebookconnect/FacebookConnectPlugin.h:11:9: fatal error: 'FacebookSDK/FacebookSDK.h' file not found
#import 
^
1 error generated.
```

That's the same error - missing link to the Facebook.framework

**Comment by bluepioupiou** [comment]
Hmmm ok I get the error, but as I said, it works perfectly with the 0.10.1 version on PGB and not with the 0.11.0...

**Comment by dankingston** [comment]
I've also hit this problem (using PhoneGap Build). My config.xml looks like this:

```
<gap:plugin name="com.phonegap.plugins.facebookconnect" source="plugins.cordova.io" version="0.11.0">
    <param name="APP_ID" value="appid" />
    <param name="APP_NAME" value="appname" />
</gap:plugin>
```

The same approach works for version 0.9.0, but not 0.10.1.

I know there's no longer support for PhoneGap Build, but if anyone could help point me in the right direction it would be a big help! What has changed between 0.9.0 and 0.10.1 that breaks the build? 

I'm happy to contribute and upload my own fork to cordova.io to get this working, but I don't really know where to start.

**Comment by dankingston** [comment]
Removing `custom_rules.xml` fixes the build on Android. I haven't tried iOS yet.
If anyone else is interested, I published the plugin (without `custom_rules.xml`) on plugins.cordova.io: [com.phonegap.plugins.facebookconnect.kl](http://plugins.cordova.io/#/package/com.phonegap.plugins.facebookconnect.kl)

**Comment by bluepioupiou** [comment]
Thanks for your help. It indeed works well for android but still not on iOS. Here is the error

The following build commands failed:
	CompileC build/Unlishdev.build/Release-iphoneos/Unlishdev.build/Objects-normal/armv7/FacebookConnectPlugin.o Unlishdev/Plugins/com.phonegap.plugins.facebookconnect.kl/FacebookConnectPlugin.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

**Comment by jfaris** [comment]
I found that removing the `custom_rules.xml` file would give bad builds for me locally because the built files weren't copied into the final apk.  To make it work both on PGB and locally I added `erroronmissingdir="false"` to the `fileset` element in`custom_rules.xml` so that the ant-build directory is only copied if it exists.

I'm not sure why PGB is using `bin` for output while locally I get `ant-build` with the same version of the Android build tools.

@aogilvie Does this solution work for you? I'll happily make a pull request if so.

@imaffett Is there a better way to fix this?  You have a much better understanding of the android build tools than I do.

**Comment by bau720123** [comment]
hi @jfaris 
I use your plugin in PGB 3.7
http://plugins.cordova.io/#/package/jfaris.com.phonegap.plugins.facebookconnect
```
<gap:plugin name="jfaris.com.phonegap.plugins.facebookconnect" version="0.11.0-jfaris.0" source="plugins.cordova.io">
<param name="APP_ID" value="1111" />
<param name="APP_NAME" value="2222" />
</gap:plugin>
```
although Android build success but iOS still build fail
is it normal about this (reason) ?
https://github.com/Wizcorp/phonegap-facebook-plugin/blob/develop/platforms/pg-build/README.md

**Comment by jfaris** [comment]
@bau720123 It builds for me on both iOS and Android using that custom version.

Can you build locally?

**Comment by bau720123** [comment]
hi @jfaris 
I don't know how to build locally
I am just use cloud build (build.phonegap.com)

**Comment by jfaris** [comment]
@bau720123 Can you post a link to a copy of the build log for iOS?

**Comment by bau720123** [comment]
hi @jfaris 
this is the ios's log information (you can use your own explorer to see it or find the keyword "jfaris")
http://www.littlebau.com/ios_log_jfaris.txt

**Comment by bau720123** [comment]
hi @jfaris 
anything unclear ?

**Comment by jfaris** [comment]
@bau720123 Works for me... I don't know what is causing that error for you.  I tried using PhoneGap 3.7.0 and 3.6.3 and both work.  Sorry I can't help more.

**Comment by vkeepe** [comment]
Since the libraries are symlink if you try to go into the library platforms/ios/FacebookSDK.framework/Versions/Current you will see your problem.

**Comment by bau720123** [comment]
hi @vkeepe 
but...I don't know how to fix all the symlink
because I just use PGB (build.phonegap.com)

**Comment by bau720123** [comment]
hi @jfaris 
can you give me your config.xml and let me test in my project
if after I use your config.xml and build success in my project that it could be my config.xml's problem
In other words...it could be PGB's problem

**Comment by vkeepe** [comment]
It is not issue of config.xml. Main issue is how git handles symlink:
http://stackoverflow.com/questions/11662868/what-happens-when-i-clone-a-repository-with-symlinks-on-windows

Go to the folder on your local drive where you got the plugin via git clone. For example you can try to go inside a directory FacebookSDK.framework/Resources

https://github.com/Wizcorp/phonegap-facebook-plugin/tree/master/platforms/ios/FacebookSDK.framework

You will notice error (Mac in my case). The issue is when you get the symlink from git via clone.

So in mac you can remove the folder Resources and do 
ln -s ./Versions/A/Resources Resources
(above command will create correct symlink)

You need to repeat same for Headers, Resources & Versions/Current (Points to A).

**Comment by bau720123** [comment]
hi @vkeepe 
in PGB (build.phonegap.com)，it is all cloud build (it mean you don't need to do any Resources fix，I am just upload a zip file to cloud server)
that's all...

**Comment by coletek** [comment]
HI @bau720123 and @jfaris,

I'm also having this issue. I tried had "com.phonegap.plugins.facebookconnect" version 0.9.0 in my config.xml and it wouldn't build for iOS using the phonegap build service. I then heard about the apparent fix via using "jfaris.com.phonegap.plugins.facebookconnect" version "0.11.0-jfaris.0" and it still does not build. See my build log at: http://www.coletek.org/build.txt

Can anyone please advise how to make it work with "jfaris.com.phonegap.plugins.facebookconnect" or even better with "com.phonegap.plugins.facebookconnect". I logged this issue with phonegap 2 months ago, and still no fix from the leads. See my original post at:

http://community.phonegap.com/nitobi/topics/oh-geez-your-build-failed-sorry-but-a-problem-occurred-on-the-build-server-inurhw1xp8c6k

**Comment by imaffett** [comment]
@coletek - For the Intel XDK, we locked it down to a previous version that we know works.  For us, that version is 0.10.1 .  We cannot get 0.11.x to work (iOS or Android)

**Comment by coletek** [comment]
Hi @imaffett - are you talking about the version for "com.phonegap.plugins.facebookconnect" or "jfaris.com.phonegap.plugins.facebookconnect"

0.9.0 of "com.phonegap.plugins.facebookconnect" doesn't work for us, and neither does "0.11.0-jfaris.0" of "jfaris.com.phonegap.plugins.facebookconnect"

Thx mate.

**Comment by imaffett** [comment]
@coletek  - this project we are on -  "com.phonegap.plugins.facebookconnect"

**Comment by jfaris** [comment]
@coletek @bau720123 Your build failures look like they might be caused by https://github.com/phonegap/build/issues/431 (reported in this project as #830)

If you can, try changing your app name to start with an uppercase letter: iCEPIKK -> ICEPIKK

**Comment by coletek** [comment]
Hi @jfaris - interesting.... Do I have to change all the .js files, or just the name in config.xml?

**Comment by jfaris** [comment]
Just the name in config.xml, as far as I know.

**Comment by coletek** [comment]
Hi @jfaris n @bau720123 - OMFG it now works.... 5 months later n it is working... all due to a useless lowercase char bug... thx guys...

**Comment by bau720123** [comment]
hi @jfaris and @coletek 
after change the app's name to uppercase letter
these two plugins also can build success in Android and iOS
```
jfaris.com.phonegap.plugins.facebookconnect
nickreed.com.phonegap.plugins.facebookconnect
```

but !!!
after my detail survey
if you install another plugin that called
```
de.appplant.cordova.plugin.local-notification
```
it will let the Android build fail

my conclusion is
if you only install facebookconnect plugin (no mater which one) or local-notification，it will all build suucess
if you install all of them，it will build fail in Android...

**Comment by bau720123** [comment]
hi @jfaris 
for now I am using PGB (build.phonegap.com) (cli-5.1.1 version with all latest core plugin from npm)
but it will appear the new error message
```
clean:
[dependency] Library dependencies:
[dependency] 
[dependency] ------------------
[dependency] Ordered libraries:
[dependency] 
[dependency] ------------------
[dependency] Found 2 versions of android-support-v4.jar in the dependency list,
[dependency] but not all the versions are identical (check is based on SHA-1 only at this time).
[dependency] All versions of the libraries must be the same at this time.
[dependency] Versions found are:
[dependency] Path: /project/jfaris.com.phonegap.plugins.facebookconnect/phonegap-FacebookLib/libs/android-support-v4.jar
[dependency] 	Length: 758727
[dependency] 	SHA-1: efec67655f6db90757faa37201efcee2a9ec3507
[dependency] Path: /project/libs/android-support-v4.jar
[dependency] 	Length: 987314
[dependency] 	SHA-1: 9b6a9a9078af571732159b904ad423b03b7cc786

BUILD FAILED
/home/ec2-user/android-sdk/tools/ant/build.xml:573: Jar mismatch! Fix your dependencies
```

**Comment by MaicolBen** [comment]
@bau720123 The next packages are not longer available on phonegap build: 
'jfaris.com.phonegap.plugins.facebookconnect
nickreed.com.phonegap.plugins.facebookconnect'

the 0.12.0 version solves this problem?

**Comment by yarontt** [comment]
Using PGB with cli-6.3.0 I get this error:
Zooz/Plugins/cordova-plugin-facebookconnect-orlando/FacebookConnectPlugin.h:11:9: fatal error: 'FacebookSDK/FacebookSDK.h' file not found

In my config.xml I have:
  <plugin name="cordova-plugin-facebookconnect-orlando" spec="0.11.0" source="npm" >
      <param name="APP_ID" value="XXXX" />
      <param name="APP_NAME" value="XXXX" />
  </plugin>


Any ideas how this can be solved?
(I can't play around with synlinks since I'm using PGB)

thanks
